namespace NServiceBus.Transport.AzureServiceBus.TransportTests;

using System;
using System.Reflection;
using System.Threading.Tasks;
using Azure.Messaging.ServiceBus;
using NServiceBus.TransportTests;
using NUnit.Framework;

[TestFixture]
public class When_processing_a_message_sent_without_explicit_message_id : NServiceBusTransportTest
{
    [Test]
    public async Task Should_use_auto_assigned_broker_message_id()
    {
        var messageReceived = CreateTaskCompletionSource<MessageContext>();

        await StartPump((context, _) =>
            {
                messageReceived.SetResult(context);
                return Task.CompletedTask;
            },
            (_, _) => Task.FromResult(ErrorHandleResult.Handled), TransportTransactionMode.ReceiveOnly);

        await using var client = new ServiceBusClient(ConfigureAzureServiceBusTransportInfrastructure.ConnectionString);

        var sender = client.CreateSender(InputQueueName);

        const string nsbMessageId = "nsb-generated-id";

        // until we can make the field protected in the core NServiceBusTransportTest base class
        var testId = (string)typeof(NServiceBusTransportTest)
            .GetField("testId", BindingFlags.Instance | BindingFlags.NonPublic)!
            .GetValue(this)!;

        var message = new ServiceBusMessage(BinaryData.Empty)
        {
            ApplicationProperties =
            {
                { Headers.MessageId, nsbMessageId },
                { "TransportTest.TestId", testId }
            }
        };

        await sender.SendMessageAsync(message, TestTimeoutCancellationToken);

        var messageContext = await messageReceived.Task;

        await StopPump();

        var receivedMessage = messageContext.Extensions.Get<ServiceBusReceivedMessage>();

        Assert.Multiple(() =>
        {
            Assert.That(receivedMessage.MessageId, Is.Not.Null.And.Not.Empty, "Message Id should be auto generated by azure service bus");
            Assert.That(receivedMessage.MessageId, Is.EqualTo(messageContext.NativeMessageId));
            Assert.That(receivedMessage.MessageId, Is.Not.EqualTo(nsbMessageId));
        });
    }
}